version: 0.1
application:
  name: Periodic Table
  language: 'python:3.10.0'
  ports:
    - port: 8000
      service: true
      ingress: true
      ingressPath: /
build:
  commands:
    - cmd: pip3
      args:
        - install
        - Kivy
        - kivymd
exec:
  commands:
    - cmd: cat
      args:
        - README
    - cmd: /docker-entrypoint.sh
      args:
        - nginx
        - '-g'
        - daemon off;
